## This section has mandatory variables
## You must provide a value for these
## If you don't provide a value for these variables, the chart installation will not proceed

## The domain name or Public IP address
## The domain name should start with http or https
## For example https://example.com
domain: "https://abc.com"

## Can be one of - azure, aws, gcloud
cloud_service_provider: "aws"

## Public storage bucket details
cloud_public_storage_accountname: "public"
cloud_public_storage_secret: "publicsecret"

## Private storage bucket details
cloud_private_storage_accountname: "private"
cloud_private_storage_secret: "privatesecret"


## This section has optional variables
## It is strongly recommended to provide a value for these
## If you don't provide a value for these variables, they will default to empty values
## If these variables are empty, some features on the application might not work as expected 
google_captcha_mobile_private_key: ""
google_captcha_private_key: ""
sunbird_mail_server_from_email: ""
sunbird_mail_server_host: ""
sunbird_mail_server_password: ""
sunbird_mail_server_port: ""
sunbird_mail_server_username: ""
sunbird_msg_91_auth: ""
sunbird_msg_sender: ""
sunbird_url_shortner_access_token: ""


## The merge domain name or Public IP address
## The merge domain name should start with http or https
## For example https://merge.example.com
merge_domain: ""